### PR TITLE
Expose device_id through session

### PR DESCRIPTION
**Pull request by musoke**
I'm submitting this separately because I'm not sure that the second commit it is optimal.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Looks fine for now, though we may introduce a first-class `DeviceId` type to ruma-identifiers in the future. I'll comment here again once ruma-api-client is updated so you can update the dependency.

**Comment by musoke** [comment]
> we may introduce a first-class DeviceId type to ruma-identifiers in the future. 

I was wondering about that.  There are actually a bunch of identifier-type things for e2ee, but it isn't clear to me that they all belong in ruma-identifiers.

I wrote something which I use in my olm crate: https://github.com/musoke/e2e-types/blob/master/src/device/mod.rs  Happy to send a PR to ruma-identifiers: it would make things simpler for me for now.

**Comment by jimmycuadra** [comment]
The Matrix spec is generally not good at specifying the requirements for identifiers. Nevertheless, I think it'd be useful to have a `DeviceId` type even if it doesn't enforce much beyond a `String`. I will add that in soon.

I created an issue for device ID grammar on the spec if you'd like to follow it: https://github.com/matrix-org/matrix-doc/issues/1257

**Comment by jplatte** [comment]
The changes from this PR have been merged in #15.

**Pull request closed without merging**
