### PR TITLE
Proposal: derive Serialize and Deserialize for Session

### PR DESCRIPTION
**Pull request by florianjacob**
to allow the user easy saving and restoring the session
between runs of their application.

Background: If you don't want to query a user's password every time, you need to store the `Session` returned from `client.log_in`, so you can provide it via `Client::https(url, Some(session))` on next start.
So as Session does not implement Serialize/Deserialize, what I currently do is something like this:

```rust
#[derive(Serialize, Deserialize, Debug)]
// copy of ruma_client::Session for deriving debug & deserialize
struct StoredSession {
    access_token: String,
    user_id: UserId,
    device_id: String,
}
impl From<Session> for StoredSession {
    fn from(session: Session) -> Self {
        StoredSession {
            access_token: session.access_token().into(),
            user_id: session.user_id().clone(),
            device_id: session.device_id().into(),
        }
    }
}

impl Into<Session> for StoredSession {
    fn into(self) -> Session {
        Session::new(self.access_token, self.user_id, self.device_id)
    }
}

…
fn main() {
    let file = fs::File::open("session.ron")?;
    let reader = io::BufReader::new(file);
    let session: StoredSession = ron::de::from_reader(reader).unwrap();
    let session = Some(session.into());
    let client = Client::https(url, session);
    …
}
```

Open to other suggestions. I guess you could argue that you could also invent your own three-line newline separated file format to store the Session manually, but if the session is actually part of a larger configuration struct you store to disk, the benefits of just using serde increase.

### CODE REVIEW

**Comment by jplatte** [comment]
I am not sure about this change because it effectively makes `Session`s current fields part of the public API. @jimmycuadra: What do you think? Is it reasonable to assume `Session` not to change significantly anymore?

**Comment by jplatte** [comment]
In the meantime, [this](https://serde.rs/remote-derive.html) *might* make your code a little nicer.

**Comment by florianjacob** [comment]
> it effectively makes `Session`s current fields part of the public API

I did not think of that consequence, admittedly. :/
While searching on how to properly do versioning with serde, I found [this issue](https://github.com/serde-rs/serde/issues/1137), but that contains nothing immediately useful to our problem here.

While serde's remote derive would spare me from having to write the From/Into and simplify the code, if the remote struct changes, it's still a breaking change as you have to adjust your local struct definition then, I think.

Can't judge how final the form of the `Session` struct is yet, but given the choice of bending over backwards to add a new `Session` field in an API-compatible way to the `new` constructor or bumping ruma-client to `0.2` and call it a breaking change, I think the latter is preferable as long as we're still < `1.0`.

Anyhow, when this is solved one way or the other, I guess I'll go and write an example on the recommended way of storing/restoring the `Session` so others can just go & copy that.

**Comment by jimmycuadra** [comment]
Saved you the trouble: https://github.com/ruma/ruma-client/commit/fa798d7a04220343db89fc6d36108ceb9d7ad1f2 :}

**Comment by florianjacob** [comment]
Thank you Jimmy! :sparkles:

**Pull request closed without merging**
